# Generated by Django 5.0.3 on 2024-05-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', '食品'), ('transport', '交通'), ('entertainment', '娛樂'), ('other', '其他')], default='other', max_length=20),
        ),
    ]
