# Generated by Django 5.0.3 on 2024-05-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('income', '收入'), ('expense', '支出')], default='expense', max_length=10),
        ),
    ]
