# Generated by Django 5.0.3 on 2024-05-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
        migrations.AddField(
            model_name='expense',
            name='bank',
            field=models.CharField(choices=[('bank1', '銀行1'), ('bank2', '銀行2'), ('cash', '現金')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', '食品'), ('transport', '交通'), ('entertainment', '娛樂'), ('other', '其他')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('income', '收入'), ('expense', '支出')], max_length=20),
        ),
    ]
